import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggle from "./components/ThemeToggle";
import { ThemeProvider } from "next-themes";
import { UserProvider } from "../context/AppContext";
import { cn } from "@/lib/utils";
import { NotificationProvider } from "./components/notifications/NotificationProvider";
import "./i18n";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "antialiased transition-colors duration-700 bg-zinc-50 dark:bg-black"
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NotificationProvider>
            <UserProvider>
              <div className="mx-auto flex min-h-screen w-1/2 flex-col max-md:w-full pt-28 pb-48 max-md:pt-20 max-md:px-4">
                <main>{children}</main>
                <ThemeToggle />
              </div>
            </UserProvider>
          </NotificationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
